# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant::Config.run do |config|
  config.vm.box = "debian_squeeze_32"
  config.vm.box_url = "http://mathie-vagrant-boxes.s3.amazonaws.com/debian_squeeze_32.box"
  config.vm.network :hostonly, "192.168.33.10"
  config.vm.forward_port 80, 8081
  # config.vm.boot_mode = :gui
  # config.vm.customize ["modifyvm", :id, "--memory", 256]

  puppet_options = [
          '--verbose',
          '--debug',
          '--graph',
          '--graphdir /vagrant/graphs'
  ].join(' ')
  config.vm.provision :puppet, :options => puppet_options do |puppet|
     puppet.module_path = ["puppet/remote-modules","puppet/modules" ]
     puppet.manifests_path = "puppet/manifests"
     puppet.manifest_file  = "jdsavocats.pp"
  end
end
